### ISSUE TITLE
白名单模式很不好用，能实现 gfwlist 的方式吗？

### ISSUE THREAD

**Issue by imoldchen** [danielfree/asus-v2ray-transparent-proxy#3]
RT，有点废流量，而且太浪费资源了。

**Comment by danielfree** [comment]
可以改造成 gfwlist 模式，但那个名单很不稳定，而且 v2ray 本身其实自带了一定的过滤，就算没在白名单里，有一部分访问会被 v2ray 判断直接放行而不会走到远程 v2ray server 的。

如果想用 gfwlist 的话，可以参考 accelerated-domains.china.conf 将所有 gfwlist 的域名加进去，并且指定到某个 ipset 里，dns 解析改成中科大那个 dns 。
