### ISSUE TITLE
加载xt_set及重启路由器后可以自动启动

### ISSUE THREAD

**Issue by dnvcupid** [danielfree/asus-v2ray-transparent-proxy#5]
目前运行`sh /jffs/dnsmasq.sh && sh /jffs/start-all.sh`

前需要先运行`modprobe xt_set`

要不然会报错`insmod: can't insert '/lib/modules/2.6.36.4brcmarm/kernel/net/netfilter/xt_set.ko': unknown symbol in module, or unknown parameter`

运行`sh /jffs/dnsmasq.sh && sh /jffs/start-all.sh`的时候需要先手动进到/jffs路径下，连接后默认的路径是`/tmp/home/root`   如果直接在这路径下直接运行`sh /jffs/dnsmasq.sh && sh /jffs/start-all.sh`会报错`cp: can't stat 'accelerated-domains.china.conf': No such file or directory`  不知道这个对后面提到的设置重启路由自动运行有影响不？

`如果想在重启路由器后可以自动启动，可以将 /jffs/start-all.sh 加入 NAT-START 脚本，你可以在路由器管理界面的 Tools->Script 页面找到设置的地方`

这个重启路由器后可以自动启动大佬能说详细点不，Tools页面没有看见Script项，只有Sysinfo及Other Settings，固件是384.4_2 小白不太了解

**Comment by danielfree** [comment]
测试环境有限，只是在我的路由器380.67上试了是没问题的，可能版本升级了之后有些变动？我需要升级版本再试试看看。

**Comment by danielfree** [comment]
@dnvcupid 我升级到384.4_2版本，直接运行也没出现 insmod 的错误，但是那个设置页面的确是没有了，不知道是不是版本更新之后把这个取消了？我回滚到380版本再看看，如果可以的话再针对384版本更新一下操作说明里的步骤

**Comment by danielfree** [comment]
已更新脚本和说明文档，请参考
